modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="aerofirmacraft_terrain.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Omnyth"
description='''
Terrain addon for Aerofirmacraft.

Current branch:
TFC fillFromNoise mixin canary.

This branch logs when TFCChunkGenerator.fillFromNoise runs.
It does not modify terrain.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tfc"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"