modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="tfc_generation_bands"
version="0.1.0-dev.2"
displayName="TFC Generation Bands"
authors="Omnyth"
description="Configurable vertical generation-band controls for TerraFirmaCraft world generation."

[[mixins]]
config="tfc_generation_bands.mixins.json"

[[dependencies.tfc_generation_bands]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.tfc_generation_bands]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.tfc_generation_bands]]
modId="tfc"
type="required"
versionRange="[4.1.1,)"
ordering="AFTER"
side="BOTH"